version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${SSH_FINGERPRINTS}
      - run:
          name: Connect with SSH
          command: |
            ssh -p ${SSH_PORT} ${SSH_USERNAME}@${SSH_HOST} ${SSH_COMMAND} -v
