version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${SSH_FINGERPRINTS}
      - run:
          name: CLI scan on SSH connection
          command: |
            echo ${CIRCLE_BUILD_NUM}
