version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${SSH_FINGERPRINTS}
      - run:
          name: CLI scan on SSH connection
          command: |
            ssh -p ${SSH_PORT} ${SSH_USERNAME}@${SSH_HOST} ${SSH_COMMAND} ${SSH_COMMAND_OPTIONS}
      - run:
          name: Transfer file on SSH connection
          command: |
            "scp -p -P ${SSH_PORT} ${SSH_USERNAME}@${SSH_HOST}:${REPORT_FILE} ~/"
